### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by muffinbarde** [nahkd123/spigot-1.17#2]
could you pls compile the whole thing again but in java version 11 instead of 16. thx (1.17 is using v11, not 16)

**Comment by nahkd123** [comment]
Well the vanilla server software requires Java 16, but if you're asking for Java 11, here it is: [spigot-1.17-0.0.1-SNAPSHOT.zip](https://github.com/nahkd123/spigot-1.17/files/6627553/spigot-1.17-0.0.1-SNAPSHOT.zip) (Yep I can't simply put JAR file in here)

In case you're confused, here is the changelog for 21w19a: [Snapshot 21w19a](https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a)
